/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tablero;

import java.awt.Button;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ray
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    
    //FondoPanel fondo = new FondoPanel();
    public Tablero() {
        //fondo.setBackground(Color.red);
        //this.setContentPane(fondo);
        initComponents();
        setIconImage(new ImageIcon("src/imagenes/icono.png").getImage());
        crearCasillas();
        //jPanel1.setBackground(new java.awt.Color(51,255,153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(836, 680));

        Logo.setBackground(new java.awt.Color(0, 51, 51));
        Logo.setIcon(new ImageIcon("src/Imagenes/icono.png"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(Logo)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Logo)
                .addContainerGap(598, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void transparancia(JButton JB){//sirve para hacer que un boton
                                        //desaparesca momentaneamente
        JB.setOpaque(false);
        JB.setContentAreaFilled(false);
        JB.setBorderPainted(false);
    }
    public void visible(JButton JB){//sirve para hacer que un boton se vea
        JB.setOpaque(true);
        JB.setContentAreaFilled(true);
        JB.setBorderPainted(true);
    }
    public void crearCasillas(){
        JButton newButton;
        JLabel newLabel;
        int x=0;
        int y=0;
        for(int i=0;i<10;i+=1){
            newLabel=null;
            switch(i){
                case 0:
                    newButton = crearBoton(x, y, 76, 58, "Libre",tipoCasilla.ESQUINA,"Free_Parking");
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "$220",tipoCasilla.ROJA,"Kentocky_Ave");
                    newLabel = crearLabel(x, y, Color.red);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "$220",tipoCasilla.ROJA,"Indiana_Ave");
                    newLabel = crearLabel(x, y, Color.red);
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "$240",tipoCasilla.ROJA,"Illinois_Ave");
                    newLabel = crearLabel(x, y, Color.red);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"B&O_Railroad");
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "$260",tipoCasilla.AMARILLO,"Atlantic_Ave");
                    newLabel = crearLabel(x, y, Color.yellow);
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "$260",tipoCasilla.AMARILLO,"Ventnor_Ave");
                    newLabel = crearLabel(x, y, Color.yellow);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$150",tipoCasilla.SERVICIO,"Water_Works");
                    break;//Servicio de agua
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "$280",tipoCasilla.AMARILLO,"Marvin_Gardens");
                    newLabel = crearLabel(x, y, Color.yellow);
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
                
            }
            
            if(newLabel!=null){
                newLabel.setVisible(true);
                jPanel1.add(newLabel);
            }
            jPanel1.add(newButton);
            x+=76;
        }
        y=0;
        for(int i=0;i<11;i++){
            newLabel=null;
            switch(i){
                case 0:
                    newButton = crearBoton(x, y, 76, 58, "<html>A la carcel<html>",tipoCasilla.ESQUINA,"Go_To_Jail");
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "$300",tipoCasilla.VERDE,"Pacific_Ave");
                    newLabel = crearLabel(x, y, Color.green);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "$300",tipoCasilla.VERDE,"No_Carolina_Ave");
                    newLabel = crearLabel(x, y, Color.green);
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "Arca",tipoCasilla.ARCA,"Community_Chest");
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "$320",tipoCasilla.VERDE,"Pennylvania_Ave");
                    newLabel = crearLabel(x, y, Color.green);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"Short_Line_R_R");
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "$350",tipoCasilla.AZUL,"Park_Place");
                    newLabel = crearLabel(x, y, Color.blue);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$75",tipoCasilla.IMPUESTO,"Luxury_Tax");
                    break;//impuesto a lujos
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "$400",tipoCasilla.AZUL,"Boardwalk");
                    newLabel = crearLabel(x, y, Color.blue);
                    break;
                case 10:
                    newButton = crearBoton(x, y, 76, 58, "Go",tipoCasilla.ESQUINA,"Go");
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
            }
  
            if(newLabel!=null){
                newLabel.setVisible(true);
                jPanel1.add(newLabel);
            }
            jPanel1.add(newButton);
            y+=58;
        }
        y-=58;
        x-=76;
        for(int i=10;i>0;i--){
            newLabel=null;
            switch(i){
                case 10:
                    newButton = crearBoton(x, y, 76, 58, "$60",tipoCasilla.CAFE,"Mediterranean_Ave");
                    newLabel = crearLabel(x, y, new java.awt.Color(204, 102, 0));//cafe
                    break;
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "Arca",tipoCasilla.ARCA,"Community_Chest");
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$60",tipoCasilla.CAFE,"Baltic_Ave");
                    newLabel = crearLabel(x, y, new java.awt.Color(204, 102, 0));//cafe
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "<html>10% or $200<html>",tipoCasilla.IMPUESTO,"Income_Tax");
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"Reading_Raiload");
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$100",tipoCasilla.CELESTE,"Oriental_Ave");
                    newLabel = crearLabel(x, y, Color.cyan);
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "$100",tipoCasilla.CELESTE,"Vermont_Ave");
                    newLabel = crearLabel(x, y, Color.cyan);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "$120",tipoCasilla.CELESTE,"Connecticut_Ave");
                    newLabel = crearLabel(x, y, Color.cyan);
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "Carcel",tipoCasilla.ESQUINA,"In_Jail");
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
            }
            if(newLabel!=null){
                newLabel.setVisible(true);
                jPanel1.add(newLabel);
            }
            jPanel1.add(newButton);
            x-=76;
        }
        y-=58;
        x=0;
        for(int i=9;i>0;i--){
            newLabel=null;
            switch(i){
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "$140",tipoCasilla.ROSA,"St_Charles_Place");
                    newLabel = crearLabel(x, y,Color.pink);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$150",tipoCasilla.SERVICIO,"Electric_Company");
                    break;//servicio de luz
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "$140",tipoCasilla.ROSA,"States_Ave");
                    newLabel = crearLabel(x, y,Color.pink);
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "$160",tipoCasilla.ROSA,"Virginia_Ave");
                    newLabel = crearLabel(x, y,Color.pink);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"Pennsylvania_R_R");
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "$180",tipoCasilla.NARANJA,"St_James_Place");
                    newLabel = crearLabel(x, y,Color.orange);
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "$180",tipoCasilla.NARANJA,"Tennessee_Ave");
                    newLabel = crearLabel(x, y,Color.orange);
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.NARANJA,"New_York_Ave");
                    newLabel = crearLabel(x, y,Color.orange);
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
            }
            if(newLabel!=null){
                newLabel.setVisible(true);
                jPanel1.add(newLabel);
            }
            jPanel1.add(newButton);
            y-=58;
        }
    }
    //los primeros dos enteros sirven para setear la localizacion
    //los segundos dos sirven para cambiar el tamaño
    public JButton crearBoton(int x,int y,
            int weight, int height,String text,
                tipoCasilla tc,String nombre){
        
        JButton newButton;
        newButton = new JButton(text);
        newButton.setBackground(new java.awt.Color(51,255,153));
        //newButton.setBackground(Color.WHITE);
        newButton.setFont(new java.awt.Font("Arial", 0, 10));
        newButton.setSize(weight,height);
        newButton.setOpaque(false);
        newButton.setLocation(x, y);
        newButton.addActionListener(new AccionCasilla(tc,nombre));
        //newButton.setVisible(false);
        return newButton;
    }
    public JLabel crearLabel(int x,int y, Color c){
        JLabel newLabel =new JLabel();
        newLabel.setBackground(c);
        newLabel.setSize(70, 20);
        newLabel.setOpaque(true);
        newLabel.setLocation(x+3, y+3);
        //newLabel.set
        
        return newLabel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    
    /*class FondoPanel extends JPanel{//hi
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
           imagen =new ImageIcon("src/Imagenes/Tablero.jpg").getImage();
           g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
           setOpaque(false);
           super.paint(g);
        }
    }*/
}
class AccionCasilla implements ActionListener{
    tipoCasilla TC;
    String nombre;
    public AccionCasilla(tipoCasilla tc,String nombre){
        this.TC=tc;
        this.nombre=nombre; 
    }
    @Override
    public void actionPerformed(ActionEvent arg0) {
        
        JOptionPane.showMessageDialog(null, "", nombre,
            JOptionPane.OK_OPTION, new ImageIcon("src/Imagenes/"+nombre+".png"));
    }
    
    
}
enum tipoCasilla{
    ESQUINA,
    CAFE,
    AMARILLO,
    CELESTE,
    ROJA,
    NARANJA,
    ROSA,
    AZUL,
    VERDE,
    FORTUNA,
    ARCA,
    ESTACION,
    SERVICIO,
    IMPUESTO;
}

