/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tablero;

import Cliente.MonopolyCliente;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JLayeredPane;

/**
 *
 * @author Ray
 */
public class Tablero extends javax.swing.JFrame {
    public MonopolyCliente refClient;
    public JButton[] arrayBotones= new JButton[40];
    public JLabel[] arrayCasas = new JLabel[44];
    public ArrayList<JLabel> arrayFichas;
    /**
     * Creates new form Tablero
     */
    
    //FondoPanel fondo = new FondoPanel();
    public Tablero() {
        
        //fondo.setBackground(Color.red);
        //this.setContentPane(fondo);
        initComponents();
        setIconImage(new ImageIcon("src/imagenes/icono.png").getImage());
        setSize(1200, 676);
        for(int i=0;i<arrayBotones.length;i++){
            arrayBotones[i]=null;
        }
        for(int i=0;i<arrayCasas.length;i++){
            arrayCasas[i]=null;
        }
        crearCasillas();
        jLabel1.setIcon(new ImageIcon("src/Imagenes/icono.png"));
        this.arrayFichas = new ArrayList<>();
        //PanelTablero.findComponentAt(WIDTH, WIDTH)
        /*for(int i=0;i<arrayBotones.length;i++){
            System.out.println(arrayBotones[i].getText()); 
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaChat = new javax.swing.JTextArea();
        lbldado1 = new javax.swing.JLabel();
        txfMensaje = new javax.swing.JTextField();
        lbldado2 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnLanzar = new javax.swing.JButton();
        lblTurno = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnProprieties = new javax.swing.JButton();
        lbDinero = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PanelTablero = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txaChat.setColumns(20);
        txaChat.setRows(5);
        jScrollPane1.setViewportView(txaChat);

        lbldado1.setBackground(new java.awt.Color(0, 0, 0));
        lbldado1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        lbldado1.setForeground(new java.awt.Color(255, 255, 255));
        lbldado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldado1.setText("0");
        lbldado1.setOpaque(true);

        lbldado2.setBackground(new java.awt.Color(0, 0, 0));
        lbldado2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbldado2.setForeground(new java.awt.Color(255, 255, 255));
        lbldado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldado2.setText("0");
        lbldado2.setOpaque(true);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLanzar.setText("Lanzar Dados");
        btnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarActionPerformed(evt);
            }
        });

        lblTurno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTurno.setText("Turno: ");

        lblUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblUser.setText("Usuario: ");

        btnProprieties.setBackground(new java.awt.Color(0, 153, 153));
        btnProprieties.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnProprieties.setText("Propiedades");
        btnProprieties.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbDinero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDinero.setText("$0");

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setText("<html>Get out of jail free");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PanelTablero.setBackground(new java.awt.Color(51, 255, 153));
        PanelTablero.setOpaque(true);
        PanelTablero.setPreferredSize(new java.awt.Dimension(836, 638));

        jLabel1.setBackground(new java.awt.Color(51, 51, 0));
        jLabel1.setText(" ");

        PanelTablero.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelTableroLayout = new javax.swing.GroupLayout(PanelTablero);
        PanelTablero.setLayout(PanelTableroLayout);
        PanelTableroLayout.setHorizontalGroup(
            PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTableroLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        PanelTableroLayout.setVerticalGroup(
            PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableroLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txfMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurno)
                            .addComponent(lblUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProprieties, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbldado2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbldado1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(1740, Short.MAX_VALUE)
                .addComponent(btnLanzar)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTurno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnProprieties, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldado2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldado1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLanzar)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try {
            // TODO add your handling code here:

            if (txfMensaje.getText().trim().equals(""))
                JOptionPane.showMessageDialog(this, "Sin mensaje para enviar");
            else{
            
                refClient.hiloCliente.writer.writeInt(2);
                refClient.hiloCliente.writer.writeUTF(txfMensaje.getText());
                txfMensaje.setText("");
            }
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    public void setDinero(int D){
        lbDinero.setText("$"+D);
    }
    private void btnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarActionPerformed
        try {
            if(refClient.hiloCliente.getIdentificador() == refClient.hiloCliente.getTurnoActual()){
                refClient.hiloCliente.writer.writeInt(3);
            }
            else{
                JOptionPane.showMessageDialog(this, "No es su turno!!!!");
            }            
            //if (btnLanzarDados.isEnabled())
            //    btnLanzarDados.setEnabled(false);
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_btnLanzarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void transparancia(JButton JB){//sirve para hacer que un boton
                                        //desaparesca momentaneamente
        JB.setOpaque(false);
        JB.setContentAreaFilled(false);
        JB.setBorderPainted(false);
    }
    public void visible(JButton JB){//sirve para hacer que un boton se vea
        JB.setOpaque(true);
        JB.setContentAreaFilled(true);
        JB.setBorderPainted(true);
    }
    private void crearCasillas(){
        JButton newButton;
        JLabel newLabel;
        int x=0;
        int y=0;
        int posicionArray=19;
        for(int i=0;i<10;i+=1){
            newLabel=null;
            switch(i){
                case 0:
                    newButton = crearBoton(x, y, 76, 58, "Libre",tipoCasilla.ESQUINA,"Free_Parking");
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "$220",tipoCasilla.ROJA,"Kentocky_Ave");
                    newLabel = crearLabel(x, y, Color.red);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "$220",tipoCasilla.ROJA,"Indiana_Ave");
                    newLabel = crearLabel(x, y, Color.red);
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "$240",tipoCasilla.ROJA,"Illinois_Ave");
                    newLabel = crearLabel(x, y, Color.red);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"B&O_Railroad");
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "$260",tipoCasilla.AMARILLO,"Atlantic_Ave");
                    newLabel = crearLabel(x, y, Color.yellow);
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "$260",tipoCasilla.AMARILLO,"Ventnor_Ave");
                    newLabel = crearLabel(x, y, Color.yellow);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$150",tipoCasilla.SERVICIO,"Water_Works");
                    break;//Servicio de agua
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "$280",tipoCasilla.AMARILLO,"Marvin_Gardens");
                    newLabel = crearLabel(x, y, Color.yellow);
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
                
            }
            
            if(newLabel!=null){
                newLabel.setVisible(true);
                PanelTablero.add(newLabel,JLayeredPane.PALETTE_LAYER);
            }
            PanelTablero.add(newButton,JLayeredPane.DEFAULT_LAYER);
            arrayBotones[posicionArray]=newButton;
            posicionArray++;
            x+=76;
        }
        y=0;
        for(int i=0;i<11;i++){
            newLabel=null;
            switch(i){
                case 0:
                    newButton = crearBoton(x, y, 76, 58, "<html>A la carcel<html>",tipoCasilla.ESQUINA,"Go_To_Jail");
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "$300",tipoCasilla.VERDE,"Pacific_Ave");
                    newLabel = crearLabel(x, y, Color.green);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "$300",tipoCasilla.VERDE,"No_Carolina_Ave");
                    newLabel = crearLabel(x, y, Color.green);
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "Arca",tipoCasilla.ARCA,"Community_Chest");
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "$320",tipoCasilla.VERDE,"Pennylvania_Ave");
                    newLabel = crearLabel(x, y, Color.green);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"Short_Line_R_R");
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "$350",tipoCasilla.AZUL,"Park_Place");
                    newLabel = crearLabel(x, y, Color.blue);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$75",tipoCasilla.IMPUESTO,"Luxury_Tax");
                    break;//impuesto a lujos
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "$400",tipoCasilla.AZUL,"Boardwalk");
                    newLabel = crearLabel(x, y, Color.blue);
                    break;
                case 10:
                    newButton = crearBoton(x, y, 76, 58, "Go",tipoCasilla.ESQUINA,"Go");
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
            }
  
            if(newLabel!=null){
                newLabel.setVisible(true);
                PanelTablero.add(newLabel,JLayeredPane.PALETTE_LAYER);
            }
            arrayBotones[posicionArray]=newButton;
            posicionArray++;
            PanelTablero.add(newButton,JLayeredPane.DEFAULT_LAYER);
            y+=58;
        }
        y-=58;
        x-=76;
        posicionArray=0;
        for(int i=10;i>0;i--){
            newLabel=null;
            switch(i){
                case 10:
                    newButton = crearBoton(x, y, 76, 58, "$60",tipoCasilla.CAFE,"Mediterranean_Ave");
                    newLabel = crearLabel(x, y, new java.awt.Color(204, 102, 0));//cafe
                    break;
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "Arca",tipoCasilla.ARCA,"Community_Chest");
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$60",tipoCasilla.CAFE,"Baltic_Ave");
                    newLabel = crearLabel(x, y, new java.awt.Color(204, 102, 0));//cafe
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "<html>10% or $200<html>",tipoCasilla.IMPUESTO,"Income_Tax");
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"Reading_Raiload");
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$100",tipoCasilla.CELESTE,"Oriental_Ave");
                    newLabel = crearLabel(x, y, Color.cyan);
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "$100",tipoCasilla.CELESTE,"Vermont_Ave");
                    newLabel = crearLabel(x, y, Color.cyan);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "$120",tipoCasilla.CELESTE,"Connecticut_Ave");
                    newLabel = crearLabel(x, y, Color.cyan);
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "Carcel",tipoCasilla.ESQUINA,"In_Jail");
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
            }
            if(newLabel!=null){
                newLabel.setVisible(true);
                PanelTablero.add(newLabel,JLayeredPane.PALETTE_LAYER);
            }
            PanelTablero.add(newButton,JLayeredPane.DEFAULT_LAYER);
            arrayBotones[posicionArray]=newButton;
            posicionArray++;
            x-=76;
        }
        y-=58;
        x=0;
        for(int i=9;i>0;i--){
            newLabel=null;
            switch(i){
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "$140",tipoCasilla.ROSA,"St_Charles_Place");
                    newLabel = crearLabel(x, y,Color.pink);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "$150",tipoCasilla.SERVICIO,"Electric_Company");
                    break;//servicio de luz
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "$140",tipoCasilla.ROSA,"States_Ave");
                    newLabel = crearLabel(x, y,Color.pink);
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "$160",tipoCasilla.ROSA,"Virginia_Ave");
                    newLabel = crearLabel(x, y,Color.pink);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.ESTACION,"Pennsylvania_R_R");
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "$180",tipoCasilla.NARANJA,"St_James_Place");
                    newLabel = crearLabel(x, y,Color.orange);
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA,"Chance");
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "$180",tipoCasilla.NARANJA,"Tennessee_Ave");
                    newLabel = crearLabel(x, y,Color.orange);
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "$200",tipoCasilla.NARANJA,"New_York_Ave");
                    newLabel = crearLabel(x, y,Color.orange);
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA,"");
            }
            if(newLabel!=null){
                newLabel.setVisible(true);
                PanelTablero.add(newLabel,JLayeredPane.PALETTE_LAYER);
            }
            arrayBotones[posicionArray]=newButton;
            posicionArray++;
            PanelTablero.add(newButton,JLayeredPane.DEFAULT_LAYER);
            y-=58;
        }
    }
    //los primeros dos enteros sirven para setear la localizacion
    //los segundos dos sirven para cambiar el tamaño
    public JButton crearBoton(int x,int y,
            int weight, int height,String text,
                tipoCasilla tc,String nombre){
        
        JButton newButton;
        newButton = new JButton(text);
        newButton.setBackground(new java.awt.Color(51,255,153));
        //newButton.setBackground(Color.WHITE);
        newButton.setFont(new java.awt.Font("Arial", 0, 10));
        newButton.setSize(weight,height);
        newButton.setOpaque(false);
        newButton.setLocation(x, y);
        newButton.addActionListener(new AccionCasilla(tc,nombre));
        //newButton.setVisible(false);
        return newButton;
    }
    public JLabel crearLabel(int x,int y, Color c){
        JLabel newLabel =new JLabel();
        newLabel.setBackground(c);
        newLabel.setSize(70, 20);
        newLabel.setOpaque(true);
        newLabel.setLocation(x+3, y+3);
        //newLabel.set
        
        return newLabel;
    }
    public JLabel crearLabelFicha(String nombre){
        JLabel newLabel = new JLabel();
        newLabel.setOpaque(true);
        newLabel.setSize(20, 20);
        ImageIcon icon = new ImageIcon("src/Imagenes/"+nombre);
        icon = new ImageIcon(icon.getImage().getScaledInstance(20, 20,Image.SCALE_DEFAULT));
        newLabel.setIcon(icon);
        return newLabel;
    }
    public void crearFicha(String nombre) throws IOException{
        JLabel newLabel =new JLabel();
        ImageIcon icon = new ImageIcon("src/Imagenes/"+nombre);
        icon = new ImageIcon(icon.getImage().getScaledInstance(60, 60,Image.SCALE_DEFAULT));     
        newLabel.setSize(60, 60);
        newLabel.setOpaque(true);
        newLabel.setIcon(icon);
        this.add(newLabel);
        newLabel.setLocation(850,480);
        //esta es la lABEL que se vera en el tablero
        JLabel LabelTablero = new JLabel();
        //icon = new ImageIcon("src/Imagenes/"+nombre);
        icon = new ImageIcon(icon.getImage().getScaledInstance(20, 20,Image.SCALE_DEFAULT));
        LabelTablero.setSize(20, 20);
        LabelTablero.setOpaque(false);
        LabelTablero.setIcon(icon);
        
        refClient.setFicha(LabelTablero);
       
    }
    
    public void setLabelInGO(int posicion,String nombre){
        int x=arrayBotones[39].getX();
        int y=arrayBotones[39].getY();
        JLabel ficha=crearLabelFicha(nombre);
        PanelTablero.add(ficha,JLayeredPane.MODAL_LAYER);
        ficha.setLocation(x+posicion, y);
        arrayFichas.add(ficha);
    }
    
    public void addMensaje(String msj){
        txaChat.append(msj + "\n");
    }
    
    public void lanzarDados(int d1, int d2){
        this.lbldado1.setText(d1 + "");
        this.lbldado2.setText(d2 + "");
    }
    
    public void setUser(String user){
        this.lblUser.setText("Usuario: " + user);
    }
    
    public void setTurno(String user){
        this.lblTurno.setText("Turno: " + user);
    }
    
    public void setRefCliente(MonopolyCliente client){
        this.refClient = client;
    }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane PanelTablero;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLanzar;
    private javax.swing.JButton btnProprieties;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDinero;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbldado1;
    private javax.swing.JLabel lbldado2;
    private javax.swing.JTextArea txaChat;
    private javax.swing.JTextField txfMensaje;
    // End of variables declaration//GEN-END:variables

    

    /*class FondoPanel extends JPanel{//hi
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
           imagen =new ImageIcon("src/Imagenes/Tablero.jpg").getImage();
           g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
           setOpaque(false);
           super.paint(g);
        }
    }*/
}
class AccionCasilla implements ActionListener{
    tipoCasilla TC;
    String nombre;
    public AccionCasilla(tipoCasilla tc,String nombre){
        this.TC=tc;
        this.nombre=nombre; 
    }
    @Override
    public void actionPerformed(ActionEvent arg0) {
        
        JOptionPane.showMessageDialog(null, "", nombre,
            JOptionPane.OK_OPTION, new ImageIcon("src/Imagenes/"+nombre+".png"));
    }
    
    
}
enum tipoCasilla{
    ESQUINA,
    CAFE,
    AMARILLO,
    CELESTE,
    ROJA,
    NARANJA,
    ROSA,
    AZUL,
    VERDE,
    FORTUNA,
    ARCA,
    ESTACION,
    SERVICIO,
    IMPUESTO;
}



