/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tablero;

import java.awt.Button;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ray
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    
    //FondoPanel fondo = new FondoPanel();
    public Tablero() {
        //fondo.setBackground(Color.red);
        //this.setContentPane(fondo);
        initComponents();
        setIconImage(new ImageIcon("src/imagenes/icono.png").getImage());
        crearCasillas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 680));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(836, 720));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void transparancia(JButton JB){//sirve para hacer que un boton
                                        //desaparesca momentaneamente
        JB.setOpaque(false);
        JB.setContentAreaFilled(false);
        JB.setBorderPainted(false);
    }
    public void visible(JButton JB){//sirve para hacer que un boton se vea
        JB.setOpaque(true);
        JB.setContentAreaFilled(true);
        JB.setBorderPainted(true);
    }
    public void crearCasillas(){
        JButton newButton;
        int x=0;
        int y=0;
        for(int i=0;i<10;i+=1){
            switch(i){
                case 0:
                    newButton = crearBoton(x, y, 76, 58, "Libre",tipoCasilla.ESQUINA);
                    break;
                case 1:
                    newButton = crearBoton(x, y, 76, 58, "Roja",tipoCasilla.ROJA);
                    break;
                case 2:
                    newButton = crearBoton(x, y, 76, 58, "Fortuna",tipoCasilla.FORTUNA);
                    break;
                case 3:
                    newButton = crearBoton(x, y, 76, 58, "Roja",tipoCasilla.ROJA);
                    break;
                case 4:
                    newButton = crearBoton(x, y, 76, 58, "Roja",tipoCasilla.ROJA);
                    break;
                case 5:
                    newButton = crearBoton(x, y, 76, 58, "Estacion",tipoCasilla.ESTACION);
                    break;
                case 6:
                    newButton = crearBoton(x, y, 76, 58, "Amarillo",tipoCasilla.AMARILLO);
                    break;
                case 7:
                    newButton = crearBoton(x, y, 76, 58, "Amarillo",tipoCasilla.AMARILLO);
                    break;
                case 8:
                    newButton = crearBoton(x, y, 76, 58, "Impuesto",tipoCasilla.IMPUESTO);
                    break;
                case 9:
                    newButton = crearBoton(x, y, 76, 58, "Amarillo",tipoCasilla.AMARILLO);
                    break;
                default:
                    newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.ESQUINA);
                
            }
            jPanel1.add(newButton);
            x+=76;
        }
        y=0;
        for(int i=0;i<11;i++){
            newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.AMARILLO);
            jPanel1.add(newButton);
            y+=58;
        }
        y-=58;
        x-=76;
        for(int i=10;i>0;i--){
            newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.AMARILLO);
            jPanel1.add(newButton);
            x-=76;
        }
        y-=58;
        x=0;
        for(int i=10;i>0;i--){
            newButton = crearBoton(x, y, 76, 58, "hola",tipoCasilla.AMARILLO);
            jPanel1.add(newButton);
            y-=58;
        }

        //fondo.add(newlabel);
        //for(int i=0;i<5;i++){
        /*newButton = crearBoton(x, y, 76, 58, "hola");
        jPanel1.add(newButton);
        x=0;
        newButton = crearBoton(x, y, 76, 58, "hola");
        jPanel1.add(newButton);
        y=0;
        newButton = crearBoton(x, y, 76, 58, "hola");
        jPanel1.add(newButton);
        x=684;
        newButton = crearBoton(x, y, 76, 58, "hola");
        jPanel1.add(newButton);*/
    }
    //los primeros dos enteros sirven para setear la localizacion
    //los segundos dos sirven para cambiar el tamaño
    public JButton crearBoton(int x,int y,
            int weight, int height,String text,tipoCasilla tc){
        
        JButton newButton;
        JLabel newLabel;
        newButton = new JButton(text);
        newButton.setBackground(new java.awt.Color(51,255,153));
        newButton.setFont(new java.awt.Font("Tahoma", 0, 10));
        newButton.setSize(weight,height);
        newButton.setOpaque(false);
        newButton.setLocation(x, y);
        newButton.addActionListener(new AccionCasilla(tc));
        //newButton.setVisible(false);
        
        newLabel =new JLabel();
        newLabel.setBackground(Color.red);
        newLabel.setSize(70, 20);
        newLabel.setOpaque(true);
        newLabel.setLocation(x+3, y+3);
        jPanel1.add(newLabel);
        return newButton;
    }
    public JLabel crearLabel(){
        JLabel newLabel =new JLabel();
        
        return newLabel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    
    /*class FondoPanel extends JPanel{//hi
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
           imagen =new ImageIcon("src/Imagenes/Tablero.jpg").getImage();
           g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
           setOpaque(false);
           super.paint(g);
        }
    }*/
}
class AccionCasilla implements ActionListener{
    tipoCasilla TC;
    public AccionCasilla(tipoCasilla tc){
        this.TC=tc;
    }
    @Override
    public void actionPerformed(ActionEvent arg0) {
        switch (TC){
            case ESQUINA:
                JOptionPane.showMessageDialog(null, "Esquina");
                break;
            case CAFE:
                break;
            case AMARILLO:
                JOptionPane.showMessageDialog(null, "Amarillo");
                break;
            case CELESTE:
                break;
            case ROJA:
                JOptionPane.showMessageDialog(null, "Roja");
                break;
            case NARANJA:
                break;
            case ROSA:
                break;
             case AZUL:
                break;
            case FORTUNA:
                JOptionPane.showMessageDialog(null, "Fortuna");
                break;
            case ARCA:
                break;
            case ESTACION:
                JOptionPane.showMessageDialog(null, "Estacion");
                break;
            case IMPUESTO:
                JOptionPane.showMessageDialog(null, "Impuesto");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Hola XD");
        }
        
    }
    
    
}
enum tipoCasilla{
    ESQUINA,
    CAFE,
    AMARILLO,
    CELESTE,
    ROJA,
    NARANJA,
    ROSA,
    AZUL,
    VERDE,
    FORTUNA,
    ARCA,
    ESTACION,
    IMPUESTO;
}

